### ISSUE TITLE
String equals method works, but curious

### ISSUE THREAD

**Issue by justinalucard** [craiggwilson/fluent-mongo#38]
I tried to use the Equals method like this.

```
Collection.AsQueryable<Account>.FirstOrDefault(x => x.Username.Equals("justin", StringComparison.OrdinalIgnoreCase));
```

Throw an exception:
System.NotSupportedException : The string method Equals is not supported.

Ok.I change a little above.

```
Func<Account, bool> func = x => x.Username.Equals("justin", StringComparison.OrdinalIgnoreCase);
Collection.AsQueryable<Account>.FirstOrDefault(func);
```

It works fine.
Could someone can tell me why?

**Comment by craiggwilson** [comment]
Yeah, that is very odd.  I have to wonder if it is pulling back all the data and running the func locally.  You could turn on profiling to see what query gets sent to the database.

**Comment by craiggwilson** [comment]
If you want a case-insensitive search, you can use a regular expression.  This is natively supported by mongodb and can even take advantage of an index if there isn't a wildcard at the beginning.

**Comment by RobThree** [comment]
Maybe it's best (but I'm no Linq expert) to throw an exception on all "XXXIgnoreCase" options? Altough it's logical that these methods cannot be 'translated' to Mongo because mongo is case-sensitive, it did had me stumped for a little while before I realised it wasn't going to work.
An alternative would be to translate all XXXIgnoreCase overloads of Equals (but also StartsWith, EndsWith, Contains etc.) to a RegEx variant? I'm just thinking aloud...
